-- MySQL Script generated by MySQL Workbench
-- 05/07/19 06:55:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbventaslaravel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbventaslaravel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbventaslaravel` DEFAULT CHARACTER SET utf8 ;
USE `dbventaslaravel` ;

-- -----------------------------------------------------
-- Table `dbventaslaravel`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbventaslaravel`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `descripcion` VARCHAR(256) NULL COMMENT '',
  `condicion` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idcategoria`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbventaslaravel`.`talla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbventaslaravel`.`talla` (
  `idtalla` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idtalla`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbventaslaravel`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbventaslaravel`.`articulo` (
  `idarticulo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idcategoria` INT NOT NULL COMMENT '',
  `idtalla` INT NULL COMMENT '',
  `codigo` VARCHAR(50) NULL COMMENT '',
  `nombre` VARCHAR(100) NOT NULL COMMENT '',
  `stock` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(512) NULL COMMENT '',
  `marca` VARCHAR(45) NULL COMMENT '',
  `modelo` VARCHAR(45) NULL COMMENT '',
  `imagen` VARCHAR(50) NULL COMMENT '',
  `estado` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`idarticulo`)  COMMENT '',
  INDEX `fk_articulo_categoria_idx` (`idcategoria` ASC)  COMMENT '',
  INDEX `fk_articulo_talla_idx` (`idtalla` ASC)  COMMENT '',
  CONSTRAINT `fk_articulo_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `dbventaslaravel`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulo_talla`
    FOREIGN KEY (`idtalla`)
    REFERENCES `dbventaslaravel`.`talla` (`idtalla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbventaslaravel`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbventaslaravel`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_persona` VARCHAR(20) NOT NULL COMMENT '',
  `nombre` VARCHAR(100) NOT NULL COMMENT '',
  `tipo_documento` VARCHAR(20) NULL COMMENT '',
  `num_documento` VARCHAR(15) NULL COMMENT '',
  `direccion` VARCHAR(70) NULL COMMENT '',
  `telefono` VARCHAR(15) NULL COMMENT '',
  `email` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`idpersona`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbventaslaravel`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbventaslaravel`.`ingreso` (
  `idingreso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idproveedor` INT NOT NULL COMMENT '',
  `tipo_comprobante` VARCHAR(20) NOT NULL COMMENT '',
  `serie_comprobante` VARCHAR(7) NULL COMMENT '',
  `num_comprobante` VARCHAR(10) NOT NULL COMMENT '',
  `fecha_hora` DATETIME NOT NULL COMMENT '',
  `impuesto` DECIMAL(4,2) NOT NULL COMMENT '',
  `estado` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`idingreso`)  COMMENT '',
  INDEX `fk_ingreso_persona_idx` (`idproveedor` ASC)  COMMENT '',
  CONSTRAINT `fk_ingreso_persona`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `dbventaslaravel`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbventaslaravel`.`detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbventaslaravel`.`detalle_ingreso` (
  `iddetalle_ingreso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idingreso` INT NOT NULL COMMENT '',
  `idarticulo` INT NOT NULL COMMENT '',
  `cantidad` INT NOT NULL COMMENT '',
  `precio_compra` DECIMAL(11,2) NOT NULL COMMENT '',
  `precio_venta` DECIMAL(11,2) NOT NULL COMMENT '',
  PRIMARY KEY (`iddetalle_ingreso`)  COMMENT '',
  INDEX `fk_detalle_ingreso_idx` (`idingreso` ASC)  COMMENT '',
  INDEX `fk_detalle_ingreso_articulo_idx` (`idarticulo` ASC)  COMMENT '',
  CONSTRAINT `fk_detalle_ingreso`
    FOREIGN KEY (`idingreso`)
    REFERENCES `dbventaslaravel`.`ingreso` (`idingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_ingreso_articulo`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `dbventaslaravel`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbventaslaravel`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbventaslaravel`.`vendedor` (
  `idvendedor` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_vendedor` VARCHAR(20) NOT NULL COMMENT '',
  `nombre` VARCHAR(100) NOT NULL COMMENT '',
  `tipo_documento` VARCHAR(20) NULL COMMENT '',
  `num_documento` VARCHAR(15) NULL COMMENT '',
  `direccion` VARCHAR(70) NULL COMMENT '',
  `telefono` VARCHAR(15) NULL COMMENT '',
  `email` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`idvendedor`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbventaslaravel`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbventaslaravel`.`tienda` (
  `idtienda` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `descripcion` VARCHAR(256) NULL COMMENT '',
  `direccion` VARCHAR(256) NULL COMMENT '',
  `condicion` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idtienda`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbventaslaravel`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbventaslaravel`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idcliente` INT NOT NULL COMMENT '',
  `idvendedor` INT NOT NULL COMMENT '',
  `idtienda` INT NOT NULL COMMENT '',
  `tipo_comprobante` VARCHAR(20) NOT NULL COMMENT '',
  `serie_comprobante` VARCHAR(7) NOT NULL COMMENT '',
  `num_comprobante` VARCHAR(10) NOT NULL COMMENT '',
  `fecha_hora` DATETIME NOT NULL COMMENT '',
  `impuesto` DECIMAL(4,2) NOT NULL COMMENT '',
  `total_venta` DECIMAL(11,2) NOT NULL COMMENT '',
  `estado` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`idventa`)  COMMENT '',
  INDEX `fk_venta_cliente_idx` (`idcliente` ASC)  COMMENT '',
  INDEX `fk_venta_vendedor_idx` (`idvendedor` ASC)  COMMENT '',
  INDEX `fk_venta_tienda_idx` (`idtienda` ASC)  COMMENT '',
  CONSTRAINT `fk_venta_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `dbventaslaravel`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_vendedor`
    FOREIGN KEY (`idvendedor`)
    REFERENCES `dbventaslaravel`.`vendedor` (`idvendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_tienda`
    FOREIGN KEY (`idtienda`)
    REFERENCES `dbventaslaravel`.`tienda` (`idtienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbventaslaravel`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbventaslaravel`.`detalle_venta` (
  `iddetalle_venta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idventa` INT NOT NULL COMMENT '',
  `idarticulo` INT NOT NULL COMMENT '',
  `cantidad` INT NOT NULL COMMENT '',
  `precio_venta` DECIMAL(11,2) NOT NULL COMMENT '',
  `descuento` DECIMAL(11,2) NOT NULL COMMENT '',
  PRIMARY KEY (`iddetalle_venta`)  COMMENT '',
  INDEX `fk_detalle_venta_articulo_idx` (`idarticulo` ASC)  COMMENT '',
  INDEX `fk_detalle_venta_idx` (`idventa` ASC)  COMMENT '',
  CONSTRAINT `fk_detalle_venta_articulo`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `dbventaslaravel`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta_venta`
    FOREIGN KEY (`idventa`)
    REFERENCES `dbventaslaravel`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbventaslaravel`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbventaslaravel`.`tipo_usuario` (
  `idtipo_usuario` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idtipo_usuario`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
